os:
  - linux
  - windows
language: cpp
compiler:
  - gcc
#  - clang

addons:
  apt:
    packages:
      - gcc-avr
      - avr-libc
      - doxygen
      - cppcheck
      - cpputest
      - graphviz
      - socat
install: skip
jobs:
  allow_failures:
    - os: windows
  include:
    - stage: Check linux code
      script:
        - make
        - make docs
        - make check
        - ./.travis/run_tests.sh
    - stage: Check avr code
      script:
        - make ARCH=avr

