os:
  - linux
#  - windows
language: cpp
compiler:
  - gcc
#  - clang

addons:
  apt:
    packages:
      - gcc-avr
      - avr-libc
      - doxygen
      - cppcheck
      - cpputest
      - graphviz
      - socat
before_install:
  - pip install --user cpp-coveralls
install: skip
jobs:
  allow_failures:
    - os: windows
  include:
    - stage: Check linux code
      script:
        - make EXTRA_CPPFLAGS="--coverage"
        - make docs
        - make check
        - ./.travis/run_tests.sh
      after_success:
        - coveralls --exclude unittest --exclude tools --gcov-options '\-lp'
    - stage: Check avr code
      script:
        - make ARCH=avr

