os:
  - linux
#  - windows
language: cpp
compiler:
  - gcc
#  - clang

addons:
  apt:
    packages:
      - gcc-avr
      - avr-libc
      - doxygen
      - cppcheck
      - cpputest
      - graphviz
      - socat
before_install:
  - pip install --user cpp-coveralls
install: skip
jobs:
  allow_failures:
    - os: windows
  include:
    - stage: Check linux code
      script:
        - make
        - make docs 1> /dev/null
        - ./.travis/run_tests.sh
        - make clean
        - make EXTRA_CPPFLAGS="--coverage" check
      after_success:
        - coveralls -b . -r ./src --exclude docs --exclude unittest --exclude bld --exclude tools --exclude examples --gcov-options '\-lp'
    - stage: Check avr code
      script:
        - make ARCH=avr

