os: linux
language: cpp
compiler:
  - gcc
#  - clang

addons:
  apt:
    packages:
      - gcc-avr
      - avr-libc
      - doxygen
      - cppcheck
      - cpputest
      - graphviz
      - socat
install: skip
jobs:
  include:
    script:
      - make
      - make docs
      - make check
      - ./tools/run_tests.sh

  include:
    script:
      - make ARCH=avr
