os: linux
language: cpp
compiler:
  - gcc
#  - clang
#before_install:
#  - sudo apt-get install -y doxygen cppcheck cpputest graphviz socat

addons:
  apt:
    packages:
      - doxygen
      - cppcheck
      - cpputest
      - graphviz
      - socat
install: skip
script:
  - make
  - make check
  - ./tools/run_tests.sh
  - make docs
