# This is a basic workflow to help you get started with Actions

name: tinyproto CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, cpp_api ]
  pull_request:
    branches: [ master, cpp_api ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc g++ clang clang-format libsdl2-dev
          sudo apt install -y cppcheck cpputest doxygen avr-libc gcc-avr graphviz socat
          sudo pip3 install cpp-coveralls
          pip3 install --user cpp-coveralls

      # Runs a set of commands using the runners shell
      - name: Building documentation
        run: |
          make docs 1> /dev/null
          
      #
      - name: Building via gcc and running unit tests
        run: |
          make
          ./.travis/run_tests.sh
          make clean
          make ARCH=linux EXTRA_CPPFLAGS="--coverage" check
          
      - name: Upload coverage statistics
        run: |
          sudo find / -name coveralls
          echo -e "service_name: circle-ci\n" > .coveralls.yml \
          && TRAVIS_JOB_ID="#${CIRCLE_BUILD_NUM}" COVERALLS_REPO_TOKEN=4Ia7t9YDo22zQcFEnMYLh1tiWCRlBJlhk coveralls -b . \
          --exclude docs --exclude extra --exclude unittest --exclude bld --exclude tools --exclude examples --gcov-options '\-lp'
